name: deploy-store

on:
  push:
    branches:
      - master
    paths:
      - 'storeApp/**'
defaults:
  run:
    working-directory: storeApp 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: yarn install 
      - run: yarn build
        env:
          PRODUCTION_DOMAIN: ${{ secrets.PRODUCTION_DOMAIN }}
     
      - run: aws s3 sync config/dist s3://${{secrets.AWS_S3_BUCKET_NAME}}/store/latest
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}} 
          AWS_DEFAULT_REGION: us-east-1